export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // CORS Preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': '*',
          'Access-Control-Max-Age': '86400'
        }
      });
    }

    // POST /proxy - 動態代理
    if (request.method === 'POST' && url.pathname === '/proxy') {
      try {
        const body = await request.json();
        
        // 使用用戶提供的 target_url 或環境變數
        const targetBase = body.target_url || env.TARGET_URL;
        const apiKey = body.key || env.API_KEY;
        
        if (!targetBase) {
          return new Response(JSON.stringify({ error: 'Missing target_url' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
          });
        }

        if (!apiKey) {
          return new Response(JSON.stringify({ error: 'Missing API key' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
          });
        }

        // 構建目標 URL
        const targetUrl = new URL(targetBase);
        targetUrl.searchParams.set('key', apiKey);
        const apiOutputUrl = targetUrl.href.replace(apiKey, 'HIDDEN_KEY');

        // 構建 Gemini 請求 body
        const reqBody = {
          contents: [{
            role: 'user',
            parts: [{ text: body.prompt || '' }]
          }],
          generationConfig: {
            response_mime_type: body.response_mime_type || 'image/png',
            temperature: body.temperature || 0.7
          }
        };

        // 代理請求
        const headers = new Headers();
        headers.set('Content-Type', 'application/json');
        headers.set('Accept', 'application/json');

        const proxyReq = new Request(targetUrl.href, {
          method: 'POST',
          headers: headers,
          body: JSON.stringify(reqBody)
        });

        const resp = await fetch(proxyReq);
        let data = await resp.json();

        // OpenAI 格式轉換
        const isOpenaiFormat = !!body.openai;
        if (isOpenaiFormat && data.candidates?.[0]?.content?.parts?.[0]?.inline_data?.data) {
          data = {
            created: Math.floor(Date.now() / 1000),
            data: [{
              b64_json: data.candidates[0].content.parts[0].inline_data.data,
              revised_prompt: data.promptFeedback?.blockReason || 'Generated by Gemini'
            }]
          };
        }

        // 返回結果
        return new Response(JSON.stringify(data), {
          status: resp.status,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': '*',
            'Access-Control-Expose-Headers': 'x-final-destination,x-openai-mode',
            'x-final-destination': apiOutputUrl,
            'x-openai-mode': isOpenaiFormat ? 'enabled' : 'native'
          }
        });

      } catch (error) {
        return new Response(JSON.stringify({ 
          error: error.message,
          details: error.stack 
        }), {
          status: 500,
          headers: { 
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          }
        });
      }
    }

    // 默認返回靜態資源（index.html）
    try {
      return await env.ASSETS.fetch(request);
    } catch (e) {
      return new Response('Not Found', { 
        status: 404,
        headers: { 'Access-Control-Allow-Origin': '*' }
      });
    }
  }
};
